### ISSUE TITLE
Can support hpv file format?

### ISSUE THREAD

**Issue by fingerx** [keijiro/KlakHap#12]
hello,keijiro.Is it possible to support the hpv format? Vjacob provides a conversion tool that is very easy to use. Hpv is also based on hap encoding, but it is compressed using different zip method.thanks very much.

this link:https://github.com/vjacob/ofxHPVPlayer

**Comment by keijiro** [comment]
I haven’t heard about HPV. My first impression is that it should be implemented as another plugin because it’s not directly related to HAP.

**Comment by fingerx** [comment]
yes. this is base for openframework but using hap codec. this link:https://github.com/HasseltVR/Holo_Toolset for unity hap version.thanks

**Comment by keijiro** [comment]
I’m still not sure the point. HPV and HAP use the similar technology, but they are different codec/format. Right? So I think it doesn’t make sense to suppor HPV in KlakHAP. Maybe I should start another project (KlaHPV?).

**Comment by fingerx** [comment]
There should be no need to rewrite it all, the hpv project code is also c++. The hpv project provides a complete processing tool. Tools for resource conversion are fast. I think KlakHap can be developed better. Of course it takes time. If you feel it is necessary, thank you again.
