### ISSUE TITLE
Can add klakhap support audio in time code to sync?

### ISSUE THREAD

**Issue by fingerx** [keijiro/KlakHap#13]
Hello, Can your add audio in timecode to synchronize multiple pc? thank you very much.

**Comment by keijiro** [comment]
Did you mean LTC? https://en.wikipedia.org/wiki/Linear_timecode

**Comment by fingerx** [comment]
@keijiro  yes,thanks

**Comment by keijiro** [comment]
It's on my radar, but it's difficult to implement without introducing delay. Also I think it shouldn't be implemented as a part of this project/repository -- I should start another project to support it.

**Comment by fingerx** [comment]
ok ,thanks
