### ISSUE TITLE
Dreams: Mobile support?

### ISSUE THREAD

**Issue by Zundrium** [keijiro/KlakHap#14]
Video's with alpha are quite the issue on mobile phones (mostly Android), for it to work, it needs to be trans-coded by Unity itself, files are large, quality is meh. Is there any hope to get some support for Android/iOS in the future? Or would that mean the whole library needs to be rewritten?

**Comment by keijiro** [comment]
Actually it's not difficult to port the plugin to mobiles. Do you actually think that it's practical for mobile apps? HAP needs tons of storage (some GB just for a few second of footage) and bandwidth (effectively wastes batteries), so I thought that it's just useless on mobiles.

**Comment by Zundrium** [comment]
Guess I was to unfamiliar with the codec, for some stupid reason I thought files weren't that large, found a solution using 2 MP4 videos where the second video is a gray-scale for the alpha, If the files are as large or larger than 300MB for a minute of video then no man, sorry for this ticket, should've looked better at HAP :)

**Comment by keijiro** [comment]
For example, I converted [24 second 1920x1080 video](https://vimeo.com/163535912) into HAP Alpha, it becomes 606MB. So I'm afraid that it doesn't fit your purpose.

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen for further questions.
