### ISSUE TITLE
Texture not clearing when update with HAP Alpha

### ISSUE THREAD

**Issue by max619** [keijiro/KlakHap#15]
When playing video, encoded with HAP Alpha codec via FFMpeg, old frames still visible under new rendered frame and leaving trails.

Rendered:
![Rendered](https://user-images.githubusercontent.com/26447324/55957283-9952a900-5c6e-11e9-9ed4-cb4280d15ec8.png)

Original:
![Original](https://user-images.githubusercontent.com/26447324/55957327-be471c00-5c6e-11e9-8b13-4ae151d6d0b5.png)

**Comment by keijiro** [comment]
Thanks for reporting the issue. Could you provide a minimum project that can reproduce the reported issue?

**Comment by max619** [comment]
![image](https://user-images.githubusercontent.com/26447324/55962038-d0c65300-5c78-11e9-8f2f-ac2d13f9c01a.png)
Also tried to use it in Test project still same result.
Only happens when rendering video in ui to render texture

**Comment by max619** [comment]
@keijiro pushed test project [here](https://github.com/max619/KlakHap/tree/problem/transparent-rendering-ui)

**Comment by max619** [comment]
Sent you PR request, looks like it would fix this issue
Also updated HAP Alpha videos with dynamic ones

**Comment by keijiro** [comment]
Thank you very much for providing the reproduction project and the pull request.

I realized that the HAP Player component incorrectly uses the blending shader to update a render texture for HAP Alpha sources. I fixed this issue in the latest commit (e8f037f1dfe686387a2730d97d65b716b626e005) and updated the package (v0.1.10).

I'm closing this issue now. Please feel free to reopen for further problems.
