### ISSUE TITLE
Videos encoded with the -chunks flag in ffmpeg cause Unity to silently crash on play

### ISSUE THREAD

**Issue by kkukshtel** [keijiro/KlakHap#2]
Just tested out the HAP player. Was using this command to encode videos:
`ffmpeg -i "C:\Users\kyle\Desktop\working folder\keijiro-dk-test\Assets\Depthkit\Examples\Clips\Julianne\Julianne.mp4" -codec:v hap -format hap -chunks 8 "C:\Users\kyle\Desktop\working folder\keijiro-dk-test\Assets\StreamingAssets\Julianne.mov"`

Unity kept crashing on start. I traced the issue to the DLL but obviously couldn't peek inside of it. I tried different encode presets and eventually found that the same command worked as long as I didn't specify chunk amount:

`ffmpeg -i "C:\Users\kyle\Desktop\working folder\keijiro-dk-test\Assets\Depthkit\Examples\Clips\Julianne\Julianne.mp4" -codec:v hap -format hap "C:\Users\kyle\Desktop\working folder\keijiro-dk-test\Assets\StreamingAssets\Julianne1.mov"`

Would love chunk support as to better control video decoding!

**Comment by keijiro** [comment]
I tried fixing the issue. Please replace `KlakHap.dll` in your project directory with the following file and check if it works.

[KlakHap.dll.zip](https://github.com/keijiro/KlakHap/files/2820341/KlakHap.dll.zip)

Although the issue was fixed, it hasn't been threaded yet. There is no merit for using chunks at the moment.

**Comment by kkukshtel** [comment]
Thanks for getting back! I'll try this fix out today.

With regards to chunks, we needed them for a project that we used HAP on and needed to render ~12 2K videos at a time. Setting a chunk amount resulted in a more performant scene for us vs. non-chunked encodes.

For this reason we used AVProVideo, as it [currently supports this (Section 4.6.3)](http://renderheads.com/product/avpro-video/). Would definitely love to see your player support it as well!

**Comment by keijiro** [comment]
KlakHap uses one thread per one decoder. So if you're playing 12 2K videos at a time, it utilizes multiple cores up to 12 cores. If you have more than 12 cores on your system, it might be better to use chunks.

**Comment by kkukshtel** [comment]
Oh interesting. I'm assuming here one decoder = one Monobehavior component? I haven't stress tested KlakHap against AVPro considering this — would be interesting to see!

**Comment by keijiro** [comment]
The fix was merged in the latest release.

https://github.com/keijiro/KlakHap/releases/tag/v0.1.4

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen for further issues or questions.
