### ISSUE TITLE
preload assets to ram memory

### ISSUE THREAD

**Issue by fingerx** [keijiro/KlakHap#20]
can you add a function to load all resources to memory when hard disk speed is not fast.  Memory is cheaper than the ssd hard disk, and the memory speed is much faster than the ssd hard disk.
thanks

**Comment by keijiro** [comment]
I don't agree with the statement; SSD ($0.1 per GB) is cheaper than RAM ($1 per GB).

That aside, it makes sense to add preload option to the HAP player. It would be useful when the file is small enough.

I'd like to add it to the to-do list.

**Comment by fingerx** [comment]
thanks keijiro,the price of ssd hard drives varies greatly.However, this feature is very useful. Thanks again.

**Comment by fingerx** [comment]
any news thanks

**Comment by keijiro** [comment]
This is a low priority task so please don't expect any progress on it for a while.
