### ISSUE TITLE
Video with alpha and interaction with the environment

### ISSUE THREAD

**Issue by f00br** [keijiro/KlakHap#23]
Hi Keijiro! 

Quick question about the interaction of video with alpha channel and light sources. I can't do it so that the video can interact with the environment. Could you tell me how to make the alpha video interact with light and other environmental effects?

I understand that in order for a video with alpha to be influenced by light sources, you need to put one more material. But I do not know what to put. Sorry for the stupid questions.

The only time when my alpha video started interacting with a light source - I changed the shader to Sprites/Diffuse.

But I understand that this is not quite the right move. Please tell me the right decision.

Thnx.

**Comment by keijiro** [comment]
- Create a render texture.
- Set it to a HapPlayer in Target Texture.
- Use the render texture in a material with the standard shader using the transparent rendering mode.

https://docs.unity3d.com/Manual/StandardShaderMaterialParameterRenderingMode.html

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further questions.
