### ISSUE TITLE
'event' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by jingpe** [keijiro/KlakHap#33]
hello keijiro,

platform: windows 10
unity 2019.4.4f1

C:\Program Files\Unity\Hub\Editor\2019.4.4f1\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.ugui\Runtime\UI\Core\InputField.cs(1628,40): error CS0246: The type or namespace name 'Event' could not be found (are you missing a using directive or an assembly reference?)

did i miss anything?

**Comment by jingpe** [comment]
the problem is resolved. after following the instruction on the homepage carefully. thanks.

**Comment by roozbehupwork** [comment]
What caused the issue?
