### ISSUE TITLE
Dynamically switch videos

### ISSUE THREAD

**Issue by jBachalo** [keijiro/KlakHap#35]
Hi
Thanks for providing this excellent resource to the community.
I have 2 looping videos that I simply want to switch between at runtime 
Simply calling the Open method alone with the new video file isn't sufficient to do this. 

These are the changes I made to the Open method. Will I have any garbage collection issues?

    `public void Open(string filePath, PathMode pathMode = PathMode.StreamingAssets)
        {
            if (_demuxer != null)
            {
                Debug.LogError("Stream has already been opened.");
                //return;
                 _demuxer.Dispose();// new line
                _demuxer = null; // new line
            }

            _filePath = filePath;
            _pathMode = pathMode;

            OpenInternal();
        }`

**Comment by keijiro** [comment]
> Will I have any garbage collection issues?

Yes. Other internal objects (`_stream`, `_decoder`, `_texture`, `_updater`) will be leaked.

I'd recommend destroying the `HapPlayer` component and recreate a new instance to open another file.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by jBachalo** [comment]
Thanks. Just thinking this would be a very useful feature.

**Comment by keijiro** [comment]
I think your modification is on the right track this time. Yes, it might be a useful feature, it needs extensive testing though.

**Comment by jBachalo** [comment]
Thanks. Unfortunately even with above still memory leak(s)! Based on your suggestion am creating 2nd component on same GameObject as HapPlayer
    `using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Playables;

namespace Klak.Hap{

    
public class DestroyHAP : MonoBehaviour
{
        HapPlayer _hap;
        public RenderTexture rt;

   public void DestroyComponent()
    {
        if(GetComponent<HapPlayer>() != null){
        Destroy(GetComponent<HapPlayer>());
                }
    }

    public HapPlayer CreateComponent()
    {
       _hap = gameObject.AddComponent<HapPlayer>();
            _hap.targetTexture= rt;
            _hap.targetRenderer= GetComponent<MeshRenderer>();
            return _hap;
        
    }
}

}`
