### ISSUE TITLE
Doesn't work in HDRP builds?

### ISSUE THREAD

**Issue by laurienash-fiftynine** [keijiro/KlakHap#41]
If I make a fresh HDRP project (on 2020.6), and add a klaphap video screen - it works correctly in editor, but when playing the build it shows as a white texture. (as if the video is not found).

If I follow the same steps with a Unity 3D pipeline, it works in the build correctly.

**Comment by laurienash-fiftynine** [comment]
Editor view:
<img width="816" alt="editor" src="https://user-images.githubusercontent.com/67958034/109879381-6607d180-7c6d-11eb-82db-f82d506e8342.PNG">

Build:
<img width="1920" alt="build" src="https://user-images.githubusercontent.com/67958034/109879405-70c26680-7c6d-11eb-89d2-7f9eab35723f.PNG">

**Comment by keijiro** [comment]
The sample project is only compatible with the legacy render pipeline, but the KlakHAP package itself is compatible with HDRP. I used it in several HDRP projects, like [this](https://github.com/keijiro/Abcvfx) and [this](https://github.com/keijiro/Dkvfx).

**Comment by keijiro** [comment]
I close this issue as resolved. Please feel free to reopen it for further problems.

**Comment by sergiobd** [comment]
I'm facing the same issue. Plugin works fine in Editor, but not in Builds. I get the following errors in the log:

`Fallback handler could not load library E:/Documents/EL_BEAT_BUILDS/EL BEAT_2019.3_Data/Mono/KlakHap.dll`
```
DllNotFoundException: KlakHap
  at (wrapper managed-to-native) Klak.Hap.Demuxer.KlakHap_OpenDemuxer(string)
  at Klak.Hap.Demuxer..ctor (System.String filePath) [0x00006] in <6d60e646883b4812b19f79ec2fedd3b3>:0 
  at Klak.Hap.HapPlayer.OpenInternal () [0x00007] in <6d60e646883b4812b19f79ec2fedd3b3>:0 
  at Klak.Hap.HapPlayer.LateUpdate () [0x00015] in <6d60e646883b4812b19f79ec2fedd3b3>:0 
```

I am building with Unity 2019.4LTS, for X86 platform.

**Comment by keijiro** [comment]
@sergiobd As noted on README, KlakHAP only supports the 64-bit platforms. It doesn't run on x86-32.
