### ISSUE TITLE
Turn off Texture Compression?

### ISSUE THREAD

**Issue by zyzyxdev** [keijiro/KlakHap#44]
Hi,
when playing a Hap alpha video (windows) I noticed the colors are slightly off. I think this may be due to texture compression. Is there a way to turn off compression?
(when viewing in an external video player the colors look fine)

Thanks!

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by zyzyxdev** [comment]
Thanks for the reply!
Yeah I get that. I'm just trying to find out why the colors are slightly different compared to say VLC player.
