### ISSUE TITLE
KlakHap and WebGL

### ISSUE THREAD

**Issue by micha01** [keijiro/KlakHap#45]
Hi Keijiro,

I use KlakHap to play hap videos with Path Mode Local File System. All is working well and for Unity desktop builds it is so far the best and only way if lossless scrubbing frame by frame is needed. 

Now I tried to publish a WebGL build. But as soon as a hap video should be opened WebGL stops and a long bug report will be thrown out. I tried Path Mode Streaming Asset, but had no success.  The same thing happens with standard Unity mp4 video player and local file system. As I read in serveral posts the problem can be solved by loading videos from url.

My question: Is there a way in KlakHap to play hap videos in WebGL? For example with Path Mode URL instead of Streaming Asset or Local File System?

Thanks

**Comment by keijiro** [comment]
As noted on README, KlakHap only supports Windows, macOS and Linux builds. WebGL is not supported.
