### ISSUE TITLE
filePath inaccessible

### ISSUE THREAD

**Issue by lejeanf** [keijiro/KlakHap#46]
Hello and thx for your amazing work.
Quick note: it would be very usefull to have access to the path variable in HapPlayer:

public string filePath 
{
    get { return _filePath; }
    set { _filePath = value; }
}

**Comment by lejeanf** [comment]
nevermind

**Comment by lejeanf** [comment]
It would be usefull to be able to change the path externaly as to switch videos.

**Comment by keijiro** [comment]
You can use `resolvedFilePath` to get the file path.

https://github.com/keijiro/KlakHap/blob/master/Packages/jp.keijiro.klak.hap/Runtime/HapPlayer.cs#L80

It's read-only because you can't change the file path while streaming. You should create another stream to use a different file path.
