### ISSUE TITLE
.mov video is white blank only in build

### ISSUE THREAD

**Issue by tanakawatanabe** [keijiro/KlakHap#47]
I'm using HAP Player for in-game TV, projector, etc.

![スクリーンショット 2024-05-16 053145](https://github.com/keijiro/KlakHap/assets/12188650/06a0dfd8-9726-4bff-b6ca-7353cf19ddc4)
I changed Path Mode to "Local File System" because StreamingAssets folder is accessible in build and the movie in it is openable by explorer,
so it could cause spoiler to some users by mistake.
In editor it shows video correctly, both in edit mode and play mode.
But it becomes totally white blank when it comes to the build.

This doesn't happen when I put video on StreamingAssets folder and set Path Mode as well,
but like I said above I'd like to use Local File System mode.

Unity 2021.3.8f HDRP DXR
KlakHAP 0.1.20

**Comment by keijiro** [comment]
A simple answer is "You can't do it in that way". Files under `Assets` are not referrenceable as an individual file in runtime.

You have to implement a custom solution to completely hide those files from users. Or you can change the `.mov` suffix to another one like `.blah` (users can peek it by renaming them, though).

**Comment by tanakawatanabe** [comment]
Thx for the reply and understood.
I searched some forums and it looks like storing videos in AssetBundle is the only way to avoid easy peeking.
I've never used this feature and not sure it works with HAP Player well but I'll look into it.

**Comment by keijiro** [comment]
Unfortunately, you can't use the Asset Bundles for this purpose. In short, it's not used for streaming.

**Comment by tanakawatanabe** [comment]
Alright, I have no choice then.
Thanks for the quick response.
