### ISSUE TITLE
Video stops playing after a few seconds

### ISSUE THREAD

**Issue by gl2888** [keijiro/KlakHap#5]
Playing a 6144x3072 60FPS HAP.mov.

Plays well, to begin with, but after 5seconds or so the image stops and strange compression artifacts begin.

![image](https://user-images.githubusercontent.com/45855131/52411773-ca7af580-2ad4-11e9-8ed2-daf36333ce6c.png)

Thanks for your help!

**Comment by keijiro** [comment]
Thank you for the report.

- What is the target platform and graphics API?
- Could you provide a video file that can reproduce the issue?

**Comment by gl2888** [comment]
Thanks for the fast reply. 

- We are targeting Windows 10 with automatic graphics API.
- Running RTX2080 on i9 with 64GB RAM. File running from M.2 disk.
- I can provide the file, however, it is over 50GB. I can send a smaller file -perhaps 600 frames privately?

This initial test was done on the test scene, ultimately we are looking to implement for VR playback on Vive Pro headset within a larger scene with realtime objects.

Thanks

**Comment by keijiro** [comment]
Thanks for the clarification. If the smaller version also reproduces the issue, it would be very helpful. I'll try to recreate the test data on my side too, but I'd appreciate if you could provide it.

**Comment by keijiro** [comment]
I managed to reproduce the issue on my side. You don't have to bother to provide the test data.

![screenshot](https://i.imgur.com/3N6zDQRl.jpg)

**Comment by keijiro** [comment]
I fixed this issue in v0.1.7. Please notify me if it still reproduces.

https://github.com/keijiro/KlakHap/releases

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen if it still reproduces.
