### ISSUE TITLE
request function

### ISSUE THREAD

**Issue by fingerx** [keijiro/KlakHap#6]
thanks for that.Using klakhap play hap is good but cant find method get current frame index in playing state. and can you add example to show how using external time mode,thanks very much.I want the host to play the video and then the other machines play it through the received sequence frame number. Thanks again, if possible.

**Comment by keijiro** [comment]
To get the current frame index:

```
var player = GetComponent<HapPlayer>();
var index = player.time * player.frameCount / player.streamDuration;
```

For more details, please see "How to control playback" in README and the [scripting example](https://github.com/keijiro/KlakHap/blob/master/Assets/Test/ScriptingTest.cs).

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further questions.

**Comment by fingerx** [comment]
thanks very much！
