### ISSUE TITLE
error regarding StreamReader.cs 

### ISSUE THREAD

**Issue by spaul13** [keijiro/KlakHap#7]
While importing the project on windows with the unity version --> 2018.1.0b4 I am getting the following error, 
**_Assets/Klak/Hap/Runtime/Internal/StreamReader.cs(26,24): error CS1644: Feature `tuples' cannot be used because it is not part of the C# 6.0 language specification_**

can u please tell me how to resolve this issue?

**Comment by keijiro** [comment]
KlakHAP requires C# 6.0 a.k.a. ".NET 4.x Equivalent".

https://blogs.unity3d.com/2018/03/28/updated-scripting-runtime-in-unity-2018-1-what-does-the-future-hold/

Please try changing the scripting runtime version.

By the way, as I noted on README, KlakHAP only supports Unity 2018.3 or later. I'd recommend upgrading Unity version.

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen for further questions.
