### ISSUE TITLE
Dynamic Add Component HapPlayer To Gameobject Show Error

### ISSUE THREAD

**Issue by fingerx** [keijiro/KlakHap#9]
@keijiro this test code and error messages.

os:win10
unity:2018.3.6f1
plugin:v0.1.8

![snipaste_2019-02-27_11-46-14](https://user-images.githubusercontent.com/5524551/53464623-df202d00-3a85-11e9-8cd5-b84a601a3a71.png)

![snipaste_2019-02-27_11-46-53](https://user-images.githubusercontent.com/5524551/53464651-f2cb9380-3a85-11e9-9a9b-8136e7631bfd.png)

**Comment by keijiro** [comment]
This modification doesn't work; It's not enough to change the file path.

If you'd like to dynamically add a HapPlayer component, I recommend using the `Open` method [as shown in the ScriptingTest.cs example](https://github.com/keijiro/KlakHap/blob/master/Assets/Test/ScriptingTest.cs#L18). You can add the second argument to enable the `LocalFileSystem` mode.

```
var player = gameObject.AddComponent<HapPlayer>();
player.Open(fileName, HapPlayer.PathMode.LocalFileSystem );
```

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen for further questions.

**Comment by fingerx** [comment]
@keijiro  thanks
